ITEM.name = "Combat Helmet"
ITEM.description = "An armored helmet."
ITEM.longdesc = "A pre-war helmet that complimented the combat armor as the standard US Army issue for infantry. Made of metal with kevlar backing, and a cloth cover."
ITEM.model = "models/fallout/apparel/combatarmorhelmet.mdl"
ITEM.price = 15000
ITEM.isGasmask = false
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.dT = 3
ITEM.eT = 2