ITEM.name = "Desert Ranger Combat Helmet"
ITEM.description = "An effective museum piece."
ITEM.longdesc = "A riot gear helmet that was never changed over to the NCR's iconography, maintaining its origonal lighter color and green-tint optics."
ITEM.model = "models/fallout/apparel/combatrangerhelmet.mdl"
ITEM.price = 15000
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.dT = 4
ITEM.eT = 3