ITEM.name = "Legion Veteran Helmet"
ITEM.description = "A set of protective gear used by Veteran Legionaries."
ITEM.longdesc = "A batter's helmet, goggles, and full-face bandanna issued as protection primarily from the elements to the seasoned Veterans of Caesar's Legion."
ITEM.model = "models/fallout/apparel/legionwhitehelmetbase_go.mdl"
ITEM.price = 15000
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.dT = 3
ITEM.eT = 1