ITEM.name = "Legion Recruit Helmet"
ITEM.description = "An ensemble used by fresh Legion Recruits."
ITEM.longdesc = "A leather cap, goggles, and bandanna issued as protection primarily from the elements to the lowly recruits of Caesar's Legion."
ITEM.model = "models/fallout/apparel/legionbandana_go.mdl"
ITEM.price = 15000
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.dT = 2