ITEM.name = "Metal Helmet, Reinforced"
ITEM.description = "Helmet of improved steel construction."
ITEM.longdesc = "A round steel helmet that provides coverage to most of the head. Made with higher quality plates for an overall improvement in protection."
ITEM.model = "models/fallout/apparel/helmetmetalarmor.mdl"
ITEM.price = 15000
ITEM.isGasmask = false
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.dT = 4
ITEM.eT = 2