ITEM.name = "Metal Helmet"
ITEM.description = "Helmet of steel construction."
ITEM.longdesc = "A round steel helmet that provides coverage to most of the head."
ITEM.model = "models/fallout/apparel/helmetmetalarmor.mdl"
ITEM.price = 15000
ITEM.isGasmask = false
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.dT = 3
ITEM.eT = 1