ITEM.name = "Raider Blastmaster Helmet"
ITEM.description = "A worn fireman's helmet and gas mask."
ITEM.longdesc = "Once associated with heroes who brave smoke and heat to put out fires, it's now often worn by those more likely to be setting them."
ITEM.model = "models/fallout/apparel/raiderarmor04_hat.mdl"
ITEM.price = 15000
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.dT = 2
ITEM.radResist = 3