ITEM.name = "Raider Wastehound Helmet"
ITEM.description = "A burlap sack with goggles."
ITEM.longdesc = "A few pieces of burlap stitched together, with goggles and tufts of hair added. The chances of someone wearing this not being mentally disturbed are near zero."
ITEM.model = "models/fallout/apparel/helmetraider02.mdl"
ITEM.price = 15000
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.dT = 1
