ITEM.name = "T-45d Power Helmet"
ITEM.description = "A T-45 helmet for the T-45d power armor."
ITEM.longdesc = "The finely-crafted helmet of the T-45 Power Armor set. When connected to a powered suit, it can display useful information on its HUD such as a compass, low light optics, and features a bright headlamp."
ITEM.model = "models/fallout/apparel/power_armor_helmet.mdl"
ITEM.price = 15000
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.isPowerArmor = true
ITEM.dT = 6
ITEM.eT = 5
ITEM.radResist = 3