ITEM.name = "Vault Security Helmet"
ITEM.description = "A riot helmet."
ITEM.longdesc = "A solid plastic helmet with shrapnel visor issued to Vault Security Officers, making a fine addition to any ensemble."
ITEM.model = "models/fallout/apparel/vaultsecurityhelmet.mdl"
ITEM.price = 15000
ITEM.isGasmask = false
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.dT = 3
ITEM.eT = 1