ITEM.name = "Guns and Bullets"
ITEM.model = "models/fo3/misc/bookguns.mdl"
ITEM.description = "A monthly magazine centered around, you guessed it, guns and bullets, for firearm enthusiasts. Articles on proper firing stances, weapon specs, and more!"
ITEM.category = "skillbooks"
ITEM.flag = "1"
ITEM.skill = "Guns"
ITEM.price = 5
ITEM.width = 1
ITEM.height = 2
