ITEM.name = "Tumblers Today"
ITEM.model = "models/fo3/misc/booktumbler_0.mdl"
ITEM.description = "A monthly magazine often enjoyed by locksmiths, with articles on innovations in physical security devices at the time and some inside-looks at common locking mechanisms."
ITEM.category = "skillbooks"
ITEM.flag = "1"
ITEM.skill = "Lockpick"
ITEM.price = 5
ITEM.width = 1
ITEM.height = 2
