ITEM.name = "Grognak The Barbarian"
ITEM.model = "models/fo3/misc/bookgrognak_0.mdl"
ITEM.description = "A trashy comic book featuring everyone's favorite axe-swinger. Bound to be an inspiration for anybody interested in bashing skulls, be it with fist or stick."
ITEM.category = "skillbooks"
ITEM.flag = "1"
ITEM.skill = "Melee"
ITEM.price = 5
ITEM.width = 1
ITEM.height = 2
