ITEM.name = "NCR Ranger Hand-To-Hand Training Manual"
ITEM.model = "models/props_lab/bindergreenlabel.mdl"
ITEM.description = "An instructional manual that is a part of a new NCR Ranger's training regimen. Penned by Ranger Captain Greene, it contains text and illustrations on executing various throws and holds used for taking down single targets. Any idiot with a lead pipe can kill a man, Greene writes, but a professional can haul him in alive."
ITEM.category = "skillbooks"
ITEM.flag = "1"
ITEM.trait = "rangertakedown"
ITEM.traitdisplay = "the Ranger Takedown unarmed technique"
ITEM.price = 5
ITEM.width = 1
ITEM.height = 2
