ITEM.name = "Chinese Special Ops Training Manual"
ITEM.model = "models/fo3/misc/bookchinese_0.mdl"
ITEM.description = "A book written for infiltrators and other sneaky types of the People's Liberation Army, with tips for moving undetected in either a public setting or on the field. How can you read it if you don't know Chinese? Shut up!"
ITEM.category = "skillbooks"
ITEM.flag = "1"
ITEM.skill = "evasion"
ITEM.price = 5
ITEM.width = 1
ITEM.height = 2
