ITEM.name = "Practical Self Defense for Scribes"
ITEM.model = "models/props_lab/binderbluelabel.mdl"
ITEM.description = "A manual spread through the ranks of the Brotherhood of Steel, created by Scribes, for Scribes. Though the caste usually doesn't fight, they are far from defenseless; the counter-attack methods outlined in this book often see others getting themselves a copy too."
ITEM.category = "skillbooks"
ITEM.flag = "1"
ITEM.trait = "scribecounter"
ITEM.traitdisplay = "the Scribe Counter unarmed technique"
ITEM.price = 5
ITEM.width = 1
ITEM.height = 2
