ITEM.name = "Lying, Congressional Style"
ITEM.model = "models/fo3/misc/booklying_0.mdl"
ITEM.description = "An guidebook outlining common fallacies and rhetoric used by members of Congress - with case studies - to manipulate people, wording things in the least offensive way possible, and talking a lot while not saying anything."
ITEM.category = "skillbooks"
ITEM.flag = "1"
ITEM.skill = "speech"
ITEM.price = 5
ITEM.width = 1
ITEM.height = 2
