ITEM.name = "Lead Lining"
ITEM.description = "A full lead lining for body armor. Very heavy, but also very protective."
ITEM.category = "Upgrades"
ITEM.model = "models/weapons/w_suitcase_passenger.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 12000
ITEM.slot = 1
ITEM.flag = "1"
ITEM.isUpgrade = true
ITEM.weight = 1.1
ITEM.isArmorUpg = true
ITEM.radResist = 30
ITEM.weightDebuff = 1
ITEM.eT = 6
