ITEM.name = "Treated Lining"
ITEM.description = "A lightweight, radiation resistant mesh applied to body armor. Lightweight, but correspondingly does not offer much radiation protection."
ITEM.category = "Upgrades"
ITEM.model = "models/weapons/w_suitcase_passenger.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 12000
ITEM.slot = 1
ITEM.flag = "1"
ITEM.isUpgrade = true
ITEM.weight = 1.1
ITEM.isArmorUpg = true
ITEM.radResist = 5
