ITEM.name = "Shielded Lining"
ITEM.description = "A heavier duty armor lining shielded against radiation. Cumbrsome, but provides good protection."
ITEM.category = "Upgrades"
ITEM.model = "models/weapons/w_suitcase_passenger.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 12000
ITEM.slot = 1
ITEM.flag = "1"
ITEM.isUpgrade = true
ITEM.weight = 1.1
ITEM.isArmorUpg = true
ITEM.radResist = 15
ITEM.weightDebuff = 1
ITEM.eT = 4
