ITEM.name = "Large Parcel"
ITEM.description = "A large box capable of holding a number of things."
ITEM.width = 2
ITEM.height = 2
ITEM.invWidth = 4
ITEM.invHeight = 2
ITEM.flag = "1"
ITEM.price = 1000
ITEM.model = "models/props_junk/cardboard_box003a.mdl"
ITEM.weaponCategory = "back"
ITEM.exRender = true
