ITEM.name = "Assaultron Chassis MK I"
ITEM.model = "models/thespireroleplay/items/clothes/group012.mdl"
ITEM.description = "The armored chassis of an Assaultron."
ITEM.longdesc = "A set of reinforced metal plating placed on the exterior of an Assaultron. The armoring is base-model, around the level of basic infantry."
ITEM.width = 2
ITEM.height = 1
ITEM.price = 230000
ITEM.flag = "A"
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.noBusiness = true
ITEM.isHelmet = true 
ITEM.isGasmask = true
ITEM.dT = 12
ITEM.eT = 9
ITEM.newSkin = 0
ITEM.weightClass = 1
ITEM.bodyGroups = {
["outfit"] = 0,
}
ITEM.bodygroupsub = {0}