ITEM.name = "Raider Scrapper Outfit (Male)"
ITEM.model = "models/thespireroleplay/items/clothes/group052.mdl"
ITEM.replacements = "models/asais10/f3npcs/raiderarmor03_f.mdl"
ITEM.description = "An outfit for reckless ramblers."
ITEM.longdesc = "With a helmet, however crude, and some well guarded limbs, a raider type can survive the odd pistol round.. if they're lucky. This one is for males."
ITEM.width = 2
ITEM.height = 1
ITEM.price = 230000
ITEM.flag = "A"
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.noBusiness = true
ITEM.weight = 2
ITEM.dT = 4
ITEM.eT = 2
ITEM.newSkin = 0
ITEM.weightClass = 1
ITEM.bodyGroups = {
["outfit"] = 0,
}
ITEM.bodygroupsub = {0}