ITEM.name = "Radiation Suit"
ITEM.model = "models/thespireroleplay/items/clothes/group009.mdl"
ITEM.replacements = "models/thespireroleplay/humans/group009/male.mdl"
ITEM.description = "A bubble-helmeted radiation suit."
ITEM.longdesc = "An industrial-grade hazmat suit, resistant not only to radiation but also other environmental hazards, and thus not a bad choice for scavenging. Not very good against projectiles and bladed or blunt blows, however. Includes a hood that cannot be removed."
ITEM.width = 2
ITEM.height = 1
ITEM.price = 230000
ITEM.flag = "A"
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.isHelmet = true
ITEM.isGasmask = true
ITEM.noBusiness = true
ITEM.dT = 4
ITEM.eT = 4
ITEM.radResist = 30
ITEM.weight = 2
ITEM.newSkin = 0
ITEM.weightClass = 2
ITEM.bodyGroups = {
["outfit"] = 0,
}
ITEM.bodygroupsub = {0}