ITEM.name = "Raider Sadist Outfit (Female)"
ITEM.model = "models/thespireroleplay/items/clothes/group052.mdl"
ITEM.replacements = "models/player/fallout3/sadistfemaleraider.mdl"
ITEM.description = "An ensemble worn by sickos."
ITEM.longdesc = "Comprised of a little bit of leather on the torso and some spiky padding on the legs, complete with sack hood. Not very protective, but better than nothing.. mostly. This one is for females."
ITEM.width = 2
ITEM.height = 1
ITEM.price = 230000
ITEM.flag = "A"
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.noBusiness = true
ITEM.weight = 2
ITEM.dT = 6
ITEM.eT = 2
ITEM.newSkin = 0
ITEM.bodyGroups = {
["outfit"] = 0,
}
ITEM.bodygroupsub = {0}