ITEM.name = "Raider Iconoclast Armor"
ITEM.model = "models/thespireroleplay/items/clothes/group052.mdl"
ITEM.replacements = "models/asais10/f3npcs/pittraider_f.mdl"
ITEM.description = "A set of mining gear, repurposed into armor."
ITEM.longdesc = "With what appears to be an old mining suit with helmet and some extra padding, this suit offers comparable protection to a more typical metal armor, but with lighter plating to make room for heat absorbtion and lead shielding, making a more evenly balanced suit."
ITEM.width = 2
ITEM.height = 1
ITEM.price = 230000
ITEM.flag = "A"
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.noBusiness = true
ITEM.weight = 2
ITEM.dT = 10
ITEM.eT = 5
ITEM.newSkin = 0
ITEM.weightClass = 3
ITEM.bodyGroups = {
["outfit"] = 0,
}
ITEM.bodygroupsub = {0}