ITEM.name = "Recon Armor"
ITEM.model = "models/thespireroleplay/items/clothes/group053.mdl"
ITEM.description = "A set of recon armor."
ITEM.longdesc = "A lightweight armor most often seen used by Initiates in the Brotherhood of Steel, or those of higher rank that serve as scouts, but some suits find their way into wastelander hands."
ITEM.width = 2
ITEM.height = 1
ITEM.price = 230000
ITEM.flag = "A"
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.noBusiness = true
ITEM.dT = 11
ITEM.eT = 6
ITEM.dR = 5
ITEM.newSkin = 0
ITEM.weightClass = 2
ITEM.bodyGroups = {
["outfit"] = 0,
}
ITEM.bodygroupsub = {0}