ITEM.name = "Advanced Radiation Suit"
ITEM.model = "models/thespireroleplay/items/clothes/group009.mdl"
ITEM.replacements = "models/thespireroleplay/humans/group009/male.mdl"
ITEM.description = "A government-issue improved radiation suit."
ITEM.longdesc = "Although its white and orange color scheme is often associated with the Enclave whose scientists were said to use it, the Advanced Radiation Suit was in fact commissioned before the war and intended for use by military hazmat units, or issued to Vaults for exploration as an improvement to the commercial model. It offers further improved environment protection and even some light kevlar sewn into the torso and limbs, with tempered glass dome."
ITEM.width = 2
ITEM.height = 1
ITEM.price = 230000
ITEM.flag = "A"
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.isHelmet = true
ITEM.isGasmask = true
ITEM.noBusiness = true
ITEM.dT = 6
ITEM.eT = 4
ITEM.radResist = 40
ITEM.weight = 2
ITEM.newSkin = 0
ITEM.weightClass = 2
ITEM.bodyGroups = {
["outfit"] = 1,
}
ITEM.bodygroupsub = {0}