ITEM.name = "Salvaged VT-17 Power Armor"
ITEM.model = "models/fallout/apparel/power_armor.mdl"
ITEM.replacements = "models/models/adi/f4vaulttecpowerarmor/vaulttecpowerarmor.mdl"
ITEM.description = "A highly advanced set of Armor"
ITEM.longdesc = "A tall, strange design of highly advanced Power-Armor. At least, it was. It appears to have been salvaged after its fusion core went critical and fried a majority of its electronoics. It's Vault-Tec Branded, and its controls seems so simple that even a raider could maneuver them. It's surprisingly comfortable to wear, and its Helmet is directly mounted to the Armor's skeleton."
ITEM.width = 2
ITEM.height = 2
ITEM.price = 230000
ITEM.flag = "A"
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.noBusiness = true
ITEMisHelmet = true
ITEMnoUpgrade = true
ITEM.weight = 2
ITEM.dT = 27
ITEM.eT = 14
ITEM.dR = 15
ITEM.newSkin = 1
ITEM.weightClass = 4
ITEM.bodyGroups = {
["teslar"] = 1,
["teslal"] = 1,
}
ITEM.bodygroupsub = {0}