ITEM.name = "Security Armor"
ITEM.model = "models/fallout/apparel/vaultsecurity.mdl"
ITEM.replacements = "models/bloocobalt/fo3/vaulttech/101-security_09.mdl"
ITEM.description = "A set of police or private issue equipment."
ITEM.longdesc = "A set of tougher kevlar vest and impact-resistant padding, issued to both police forces to quell protests and control crowds."
ITEM.width = 2
ITEM.height = 1
ITEM.price = 230000
ITEM.flag = "A"
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.noBusiness = true
ITEM.weight = 2
ITEM.dT = 14
ITEM.eT = 3
ITEM.dR = 5
ITEM.newSkin = 0
ITEM.weightClass = 2
ITEM.bodyGroups = {
["helmet"] = 3,
}
ITEM.bodygroupsub = {0}